### ISSUE TITLE
Add ability to execute examples

### ISSUE THREAD

**Issue by foxbunny** [imba/imba-guide#3]
Add a button to execute the example snippets and see the results. Perhaps even make the examples editable on the spot? Maybe a shortcut to load the example into Scrimba?

**Comment by foxbunny** [comment]
@somebee How difficult would it be to allow Scrimba to load arbitrary Imba code through query string?

**Comment by aalemayhu** [comment]
Since the repository is being deprecated this issue no longer has to be resolved.
Please use https://github.com/imba/imba.io
